Contributors.md, README.md
Create a document where everything is recorded as contributors to the project @mvillaseco
=> Creation of contributors document

README.md
=> Url contributors 

gulpfile.js, package.json
Small addition, only to compile sass files to css.
=> [UI] Add package and gulp file

foundation/foundation.css, foundation/grid.css, foundation/index.html, foundation/layout.css, foundation/reset.css, foundation/special.css
In this branch we made the class arrangements, css alignment spaces for the foundation. Please look at the Pull Request again! 🙏🏻
=> Fix space alignment update and appointment of classes in the css

build-w-docker.sh, gulpfile.js
fix(build): delete watching change in build-w-docker and change task to run gulpfile correctly
=> Fix in build docker and gulpfile

assets/js/main.js, assets/scss/core/_colors.scss, assets/scss/templates/_footer.scss, assets/scss/templates/_guidelines.scss, assets/scss/templates/_header.scss, assets/templates/index.html
=> add footer component

assets/js/main.js
WIP
- Refactor nav js to can use in doppler webapp
- Clean unuse js
=> [refactor] header nav js

assets/js/main.js
- Check if item menu has submenu to increment header size
=> [fix] when increment header size on hover

assets/scss/core/_reset.scss, assets/scss/templates/_header.scss, assets/scss/templates/_messages-header.scss, assets/templates/index.html
fix: add reset buttons
feat: add header messages
BREAKING CHANGE: add "button" element instead "link" element in user-menu
=> Header fixes

assets/scss/core/_reset.scss, assets/scss/templates/_header.scss
fix: margins and paddings header
feat: add styles for scrollbar navigation
=> fix margins header

assets/scss/core/_colors.scss, assets/scss/core/_reset.scss, assets/scss/core/_typography.scss, assets/scss/modules/_buttons.scss, assets/scss/templates/_guidelines.scss, assets/scss/templates/_header.scss, assets/templates/index.html
feat(style): add new buttons component
CDN Link:
https://cdn.fromdoppler.com/doppler-ui-library/build32/
=> Buttons component

assets/templates/footer.html, assets/templates/header.html, assets/templates/index.html, assets/templates/messages-header.html
=> feat: create separate templates for each component

assets/scss/templates/_guidelines.scss, assets/templates/footer.html, assets/templates/header.html, assets/templates/index.html, assets/templates/messages-header.html
=> feat: add navigation for doppler ui

assets/scss/core/_typography.scss, assets/scss/templates/_signup.scss, assets/templates/signup.html
Modify structure and class signup layout for optimize html. 
http://cdn.fromdoppler.com/doppler-ui-library/build60/signup.html
=> Signup structure

assets/js/main.js, assets/scss/modules/_modal.scss, assets/templates/header.html
- Initialize all modals hidden
- Add close user menu when click in upgrade plan button
=> fix: modal interaction

assets/scss/core/_base.scss, assets/scss/core/_typography.scss, assets/scss/core/_variables.scss, assets/scss/modules/_forms.scss, assets/scss/styles.scss, assets/scss/templates/_guidelines.scss, assets/scss/templates/_header.scss, assets/templates/modal.html
Se cambiaron los elementos de formulario para visualizarlos de forma global con la estetica correcta.
=> Elements forms

assets/scss/core/_typography.scss, assets/scss/templates/_reportes.scss, assets/templates/header.html, assets/templates/index.html, assets/templates/messages-header.html, assets/templates/modal.html, assets/templates/reports-filters.html
Se agrego el header del mock nuevo de reportes mostrando los elementos html de filtros
**Nota AM:** El estilado de los componentes del formulario, queda fuera del scope de la tarea, se hará en otro PR.
=> Reports filters

assets/scss/core/_typography.scss, assets/scss/templates/_reportes.scss, assets/templates/reports-filters.html
=> feat: add input styles

assets/scss/templates/_header.scss, assets/templates/header.html
- fix header nav right to avoid inherit ul styles in modal on webapp
=> fix: header nav right to avoid inherit ul styles

assets/scss/core/_variables.scss, assets/scss/modules/_buttons.scss, assets/scss/templates/_guidelines.scss, assets/templates/index.html
=> Refactor buttons

assets/scss/templates/_guidelines.scss, assets/templates/index.html, assets/templates/signup.html
Add the html structure of the form
=> Signup form

assets/scss/templates/_messages-header.scss, assets/templates/messages-header.html
Class name modifications to use the same class name 'BE' brings
=> fix: messages header

assets/js/main.js
fix: add a way to close user menu when clicking outside it
=> DBR-91 Fix issues with user menu

assets/scss/modules/_preload.scss, assets/scss/templates/_guidelines.scss, assets/templates/footer.html, assets/templates/header.html, assets/templates/index.html, assets/templates/loading-page.html, assets/templates/messages-header.html, assets/templates/modal.html, assets/templates/reports-filters.html
Creation of preloading for the pages
=> Loading page

assets/scss/modules/_atomic-class.scss
@IgnacioRodrigues, @GusBaamonde, @damianmuti and @mvillaseco, it is a very minor PR, but, could you kindly review it anyway?
=> feat: add uppercase atomic class

assets/scss/templates/_reportes.scss, assets/templates/reports-filters.html
- Add elements html for top ranking
- Add styles for top ranking
=> Top ranking

assets/scss/templates/_reportes.scss
Hablamos con Santi y retocamos los paddings de las cajas para una visualización mas compacta.
=> feat: fix padding top ranking

assets/scss/core/_base.scss, assets/scss/modules/_forms.scss, assets/scss/templates/_signup.scss, assets/templates/login.html
- The html elements and form styles of the login were added. 
- The spaces will be normalized in another PR.
-  The header will be changed in another PR.
https://cdn.fromdoppler.com/doppler-ui-library/build155/login.html
=> feat: Added the html elements and login form styles

assets/scss/core/_variables.scss, assets/scss/templates/_signup.scss
- Normalize spaces in login and signup
https://cdn.fromdoppler.com/doppler-ui-library/build157/login.html
https://cdn.fromdoppler.com/doppler-ui-library/build157/signup.html
=> fix: normalize spaces in login and signup

assets/scss/core/_variables.scss, assets/scss/modules/_forms.scss, assets/scss/templates/_guidelines.scss, assets/scss/templates/_signup.scss, assets/templates/confirmation-page.html, assets/templates/footer.html, assets/templates/forgot-password.html, assets/templates/header.html, assets/templates/index.html, assets/templates/loading-page.html, assets/templates/login.html, assets/templates/messages-header.html, assets/templates/modal.html, assets/templates/reports-filters.html, assets/templates/signup.html
- Created layout forgot password
https://cdn.fromdoppler.com/doppler-ui-library/build162/forgot-password.html
=> Forgot password

assets/scss/templates/_footer.scss, assets/templates/footer.html
=> feat: remove link footer

assets/templates/login.html
I deleted the phrase in login and put the show password icon
=> fix: I deleted the phrase and put the show password icon

.gitignore, gulpfile.js
Updated Gulp logic
Updated .gitignore
=> fix: icon fonts not being generated

assets/scss/core/_base.scss, assets/scss/core/_variables.scss
Change de border color and color the text placeholder.
=> fix: change color in the border input and placeholder

assets/scss/core/_base.scss, assets/scss/modules/_forms.scss, assets/scss/templates/_signup.scss
- Fix for resolutions up to 768px and higher.
- We generate balanced spaces with the established variables.
https://cdn.fromdoppler.com/doppler-ui-library/build193/signup.html
=> fix: fix resolution for signup in 768px resolutions

assets/scss/core/_settings.scss, assets/scss/modules/_atomic-class.scss, assets/scss/modules/_forms.scss, assets/scss/modules/_language.scss, assets/scss/templates/_signup.scss
General adjustments of margins and paddings for 320px
Reviewed with Santiago Paolucci
=> fix: general adjustments of margins and paddings for 320px

assets/scss/core/_base.scss, assets/scss/core/_settings.scss, assets/scss/core/_typography.scss, assets/scss/core/_variables.scss, assets/scss/modules/_atomic-class.scss, assets/scss/modules/_buttons.scss, assets/scss/modules/_forms.scss, assets/scss/modules/_language.scss, assets/scss/modules/_modal.scss, assets/scss/templates/_confirmation.scss, assets/scss/templates/_guidelines.scss, assets/scss/templates/_header.scss, assets/scss/templates/_messages-header.scss, assets/scss/templates/_reportes.scss, assets/scss/templates/_signup.scss
I removed the old font size variables, replacing them with new variables in levels, impacting all the scss files. I've talked to Santiago Paolucci and he agrees.
=> Replacement of font size variables

assets/scss/modules/_forms.scss
separation of buttons in modal form DBR 175
=> feat: separation of buttons in modal form

assets/scss/core/_base.scss, assets/scss/modules/_forms.scss, assets/templates/signup.html
**Add a validation to the password field:**
1. 8 characters minimum
2. One letter
3. One number
**it adjusts to the mobile view.**
=> Feat: add a validation to the password field

assets/scss/core/_base.scss, assets/templates/signup.html
=> feat: create a container for unexpected messages

assets/scss/modules/_forms.scss
=> feat: Modify the position of the password safe icon

assets/scss/core/_variables.scss, assets/scss/modules/_backgrounds.scss, assets/scss/templates/_confirmation.scss, assets/templates/confirmation-page.html
fix(background): correction in background images
=> Correction in background imagen the confirmation page

assets/js/main.js, assets/scss/templates/_header.scss, assets/templates/header.html
- Adapt the user-menu container to be able to show it by class and not by ID, reusing the style of the container
=> BREAKING CHANGE: show notification message

assets/scss/core/_base.scss, assets/templates/login.html
=> feat: support including buttons with link style inside error messages

assets/scss/core/_variables.scss, assets/scss/templates/_reportes.scss
Create container to display the datahub messages.
This container will allow us to continue implementing the designs of the messages.
PR realated with:  https://github.com/FromDoppler/doppler-webapp/pull/151
=> Create container to display datahub messages

assets/scss/templates/_reportes.scss
Paragraphs were adjusted in their width and line-height to improve their readability (improvement)
=> feat: Paragraphs were adjusted

assets/scss/templates/_reportes.scss
=> feat: correction and alignment of boxes in the report layout

assets/scss/modules/_atomic-class.scss, assets/templates/forgot-password.html, assets/templates/login.html, assets/templates/signup.html
=> feat: add link in the logo

assets/js/main.js, assets/scss/templates/_header.scss, assets/templates/confirmation-page.html, assets/templates/header.html
Updated logic to emulate Doppler App menu.
*NOTE*: I did not do any improvements in terms of code, just focused on fixing the issue.
**DEMO:** https://cdn.fromdoppler.com/doppler-ui-library/build248/header.html
=> fix: issues with main menu

assets/scss/modules/_forms.scss, assets/templates/modal.html
Flex properties are not well supported by fieldset elements.
=> visual error in upgrade submit

assets/scss/templates/_footer.scss, assets/scss/templates/_reportes.scss
=> homogeneous visual coherence for messages and alignment of footer boxes

assets/scss/modules/_forms.scss, assets/templates/signup.html
Changed positioning of the icon. This PR is currently for testing purposes on different environments, so I'll edit it once it's ready for CR.
**EDIT**: Finally fixed the issue. Please verify, @CarlosSampedro @andresmoschini @GusBaamonde 
https://cdn.fromdoppler.com/doppler-ui-library/build268/signup.html
=> fix: issues with icon positioning

build-n-release-w-docker.sh, package-lock.json, package.json, watch-w-docker.sh
Hi team, 
This is to generate a version number and release notes based on our commit messages, as [we are already doing in Form Generator](https://github.com/MakingSense/doppler-forms-generator/releases).
The idea is having better information about what version are we using in the WebApp in each moment.
Then, I will apply the same approach to WebApp and integrate it with docker images generation.
⚠ **After now, all we will need to take care of the commit messages.**
Could you review?
```
* Merge pull request #93 from GusBaamonde/paid_account_with_no_trial_activated (538931b (https://github.com/FromDoppler/Doppler-UI-System/commit/538931b)), closes #93 (https://github.com/FromDoppler/Doppler-UI-System/issues/93)
* add a way to close user menu when clicking outside it (88973e9 …
```
=> DBR-310 - Semantic Release

assets/scss/modules/_preload.scss, assets/templates/loading-page.html
- Refactor ui library spinner styles to use in webapp to has consistency with doppler app
=> fix: refactor spinner styles

assets/scss/templates/_reportes.scss
- Fix spinner in reports rankings section to see inside the box
=> fix: reports rankings spinner style

assets/scss/templates/_header.scss, assets/templates/header.html
**Logo client manager for small resolutions**
=> Add logo client manager

assets/scss/templates/_signup.scss, assets/templates/forgot-password.html, assets/templates/login.html, assets/templates/signup.html
- Change styles in login and signup for dinamic promotions in webapp
=> refactor: change styles promotions public pages

assets/scss/templates/_signup.scss, assets/templates/forgot-password.html, assets/templates/login.html, assets/templates/signup.html
=> feat: change styles promotions public pages

assets/js/main.js
=> fix: submenu DBR-339

assets/scss/templates/_header.scss
=> feat: change height logo client manager

assets/scss/templates/_signup.scss, assets/templates/forgot-password.html, assets/templates/login.html, assets/templates/signup.html
- Add font color inherit from parent because in webapp define in parent the font color
- Fix the height for right column
=> fix: font color in promotions and height

assets/js/main.js, assets/scss/templates/_header.scss, assets/templates/header.html
Solved the :after data-count="0" @cbernat
=> feat: show notifications

assets/scss/templates/_signup.scss
Weird behavior with "page" content scroll 
http://jira.makingsense.com/browse/DBR-346
=> fix: scroll in pages public

assets/scss/helpers/_colors.scss, assets/scss/modules/_tables.scss, assets/templates/index.html, assets/templates/partials/_table-component.html
=> feat: creation of the table component

assets/scss/modules/_tables.scss, assets/templates/partials/_table-component.html
Se respeto el estilo de tabla zebra para una mejor visualización del usuario
Revisado con @santiagopaolucci
=> feat: table component state synchronizing

assets/scss/modules/_buttons.scss, assets/templates/index.html
=> feat: add button brown for academy site

assets/scss/modules/_buttons.scss, assets/templates/index.html
New state for buttons:
- Secondary button green:
- Secondary button brown:
=> Add new state for buttons

assets/scss/core/_settings.scss, assets/scss/helpers/_colors.scss, assets/scss/modules/_box.scss, assets/scss/modules/_tooltip.scss, assets/scss/templates/_guidelines.scss, assets/templates/index.html, assets/templates/partials/_tooltip-component.html
**Creation of tooltip component.**
To specify the orientation of the 'tooltip', you can use the top / right / bottom / left, classes if you need it.
=> feat: Creation of tooltip component

assets/scss/modules/_breadcrumb.scss, assets/scss/templates/_guidelines.scss, assets/templates/index.html, assets/templates/partials/_breadcrumb.html
The breadcrumb component for Shopify was created
=> Breadcrumb component

assets/scss/templates/_reportes.scss, assets/templates/reports-filters.html
- Change styles to be more reusable in all reports box
- Change names of the css classes for reausable proposites
=> fix(reports): refactor styles to work fine in traffic sources

assets/scss/templates/_reportes.scss
=> fix(reports traffic sources): box height style

assets/scss/helpers/_animations.scss, assets/scss/modules/_messages.scss, assets/scss/templates/_guidelines.scss, assets/templates/index.html, assets/templates/partials/_msj-component.html
-Creation of error messages
-Creation of succes messages
-Creation of warning messages
-Message creation for users
-Creation of animations to show them
-Markup of the messages in html
Validated with @santiagopaolucci
=> feat (messages): mixin creation for user messages

build-n-release-w-docker.sh, build-w-docker.sh
Hi team, @GusBaamonde detected this issue in the build, I will merge without review.
Now:
Before:
=> Fix build on no version

build-n-release-w-docker.sh
I forgot using `$` to refer to _versionFile_ variable.
And also the exit code was an error code:
=> chore(build): oooops

assets/scss/modules/_breadcrumb.scss, assets/templates/partials/_breadcrumb.html
Anchor change by span
Add the class nomenclature
Add padding to span
=> fix(breadcrumb): anchor change by span

assets/scss/modules/_breadcrumb.scss, assets/templates/partials/_breadcrumb.html
=> fix: remove the span so that it inherits the style of li

assets/scss/modules/_breadcrumb.scss, assets/templates/partials/_breadcrumb.html
Remove styles for specific items
=> Fix component breadcrumb

assets/scss/templates/_reportes.scss
=> fix: fix for footer in the report pages

assets/scss/templates/_guidelines.scss, assets/templates/account-message-component.html, assets/templates/animations-component.html, assets/templates/breadcrumb-component.html, assets/templates/buttons-component.html, assets/templates/confirmation-page.html, assets/templates/footer.html, assets/templates/forgot-password.html, assets/templates/header.html, assets/templates/index.html, assets/templates/integrations.html, assets/templates/layout.html, assets/templates/loading-page.html, assets/templates/login.html, assets/templates/messages-component.html, assets/templates/messages-header.html, assets/templates/modal-component.html, assets/templates/modal.html, assets/templates/partials/_navigation.html, assets/templates/preload-component.html, assets/templates/reports-filters.html, assets/templates/signup.html, assets/templates/table-component.html, assets/templates/tooltip-component.html
- the `@for` was modified to take the active menu according to the page
- The `data-name` of the html was modified to coordinate them with the menu
=> feat(navigation): the @for was modified to take the active menu

assets/scss/core/_variables.scss, assets/scss/templates/_guidelines.scss, assets/templates/table-component.html
=> feat(table component): table component ajustments

assets/scss/templates/_guidelines.scss, assets/templates/breadcrumb-component.html
=> feat(breadcrumb component): breadcrumb component ajustments

assets/scss/modules/_tooltip.scss, assets/templates/tooltip-component.html
component for report charts visits weekdays hours
- Add a mixin for the new tooltip
- Add a different animation to the new tooltip
#Checklist
=> feat(tooltip): creation of a new tooltip 

assets/scss/modules/_tooltip.scss, assets/scss/templates/_guidelines.scss, assets/templates/tooltip-component.html
add a max-content to the tooltip and accommodate its content
#Checklist
=> fix(tooltip-component): 

assets/scss/templates/_guidelines.scss, assets/templates/messages-component.html
=> feat(messages component): adaptation of the component to the new mockup

assets/scss/templates/_reportes.scss
=> fix: kpi width adjustment

assets/templates/grid-system-component.html
=> feat: text adjustment

.dependabot/config.yml
=> fix: finish release without error when no new version

assets/scss/core/_variables.scss, assets/scss/modules/_box.scss, assets/scss/modules/_grid-system.scss, assets/scss/templates/_layout.scss, assets/scss/templates/_reportes.scss
=> fix: decouple report styles

assets/scss/templates/_footer.scss, assets/templates/footer-component.html, assets/templates/partials/_navigation.html
=> feat: add new footer component

assets/scss/modules/_buttons.scss, assets/scss/modules/_grid-system.scss, assets/scss/templates/_integrations.scss, assets/templates/integrations.html
#Checklist
https://cdn.fromdoppler.com/doppler-ui-library/build671/integrations.html
Related to: https://github.com/FromDoppler/doppler-webapp/pull/628
=> fix: I removed shopify styles to reuse other webapp classes

assets/scss/modules/_forms.scss, assets/scss/modules/_tables.scss, assets/scss/templates/_integrations.scss, assets/templates/partials/_navigation.html, assets/templates/subscriber-history.html
**add the Subscriber History layout (first approach)**
**add a small class for responsive tables
add responsive layout**
**add WAI-ARIA to the search form (first approach)
quick accessibility test with chrome**
**this pr is in progress**
#Checklist
=> DW-126: feat: add the Subscriber History layout

assets/scss/modules/_forms.scss
=> DW-150 fix: arrows in select

assets/scss/templates/_header.scss, assets/templates/header.html
#Checklist
@cbernat  @javierburger
=> fix: remove the top margin of user plan container

assets/scss/core/_reset.scss, assets/scss/modules/_grid-system.scss
=> fix: 100% width of parent dp-container changed

assets/scss/modules/_images.scss
=> fix: the icons url was corrected

assets/scss/modules/_images.scss, assets/scss/templates/_subscriber-history.scss, assets/templates/subscriber-history.html
=> feat: add the table and campaign icons

assets/scss/helpers/_colors.scss, assets/scss/modules/_images.scss, assets/templates/subscriber-history.html
=> fix: add icons in campaign states

assets/js/main.js, assets/scss/helpers/_colors.scss, assets/scss/modules/_images.scss, assets/scss/templates/_subscriber-history.scss, assets/templates/subscriber-history.html
#Checklist
**Desktop**
**Tablet**
**Mobile**
=> Dw 164 campaign table header

assets/icons/arrow-next.svg, assets/icons/arrow-prev.svg, assets/scss/modules/_pagination.scss, assets/templates/subscriber-history.html
=> feat: add subscriber history pagination

assets/scss/modules/_images.scss
=> fix: icon class name fix

assets/scss/modules/_grid-system.scss, assets/scss/templates/_guidelines.scss, assets/templates/buttons-component.html
=> feat: add the button component to the new layout

assets/templates/account-message-component.html
=> fix: accommodate messages within the new layout

assets/templates/preload-component.html
=> feat: add the preload to the new layout

assets/templates/index.html
Test for release build failed. 
#Checklist
=> feat: add documentation link id

assets/scss/modules/_images.scss, assets/templates/subscriber-history.html
=> fix: icon in subscriber history

assets/scss/modules/_images.scss, assets/templates/subscriber-history.html
#Checklist
related: https://github.com/FromDoppler/doppler-webapp/pull/771
=> feat: add unanswered status in GDPR

assets/templates/notification-poc.html
Trigger release again because of uploader error
=> fix(pushPOC): fix text

assets/scss/themes/editors/colors/_colors.scss, assets/scss/themes/editors/editors.scss, assets/scss/themes/theme-dark/colors/_colors.scss, assets/scss/themes/theme-dark/theme-dark.scss, assets/templates/partials/_navigation.html, assets/templates/themes.html, gulpfile.js
- two themes were created, dark and editors
- proof of concept for dark
- the html theme was created to test colors
http://cdn.fromdoppler.com/doppler-ui-library/build770/index.html
#Checklist
=> feat: gulp tasks were created to compile a theme

assets/scss/templates/_confirmation.scss
=> fix(confirmation page): logo relocation on confirmation page

package.json
=> fix: script modification in prettier

assets/templates/login.html, assets/templates/signup.html, assets/templates/tooltip-component.html
=> fix: run prettier check on files

package-lock.json
=> fix: version prettier test

assets/js/webPushMain.js, assets/templates/notification-poc.html
Add params for public jey and serrver url to do some tests.
#Checklist
https://cdn.fromdoppler.com/doppler-ui-library/build795/notification-poc.html
=> feat(PN): add push server config and public key

Dockerfile, assets/templates/forgot-password.html, assets/templates/login.html, assets/templates/signup.html, assets/templates/tooltip-component.html, build-n-release-w-docker.sh, package-lock.json, package.json
=> Dependabot update prettier 2

Dockerfile, build-n-release-w-docker.sh, package-lock.json
=> fix: update node version for semantic release

assets/scss/templates/_confirmation.scss, assets/templates/confirmation-page.html
=> fix: replace link with a button

assets/js/webPushMain.js, test-push-notification.http
- Removed redundant code
- Add rest client test file for post documentation and testing
=> Push Notification POC: Refactor and add post example

build-n-release-w-docker.sh
Fix error in version txt not being generated, locally tested with dry-run mode.
#Checklist
=> fix(semantic-release): fix script

assets/templates/notification-poc.html
=> fix: force new version

assets/js/main.js, assets/js/webPushMain.js, assets/scss/helpers/_mixins.scss, assets/scss/modules/_tabs.scss, assets/scss/templates/_guidelines.scss, assets/templates/partials/_navigation.html, assets/templates/tabs-component.html
- add the html tabs file
- add the style for the component
- add the link in the navigation bar
#Checklist
=> Dw 305 tabs component

assets/scss/modules/_tables.scss, assets/scss/templates/_subscriber-history.scss, assets/templates/subscriber-history.html, assets/templates/tabs-component.html
=> feat: change of paddings in the tables

assets/scss/modules/_forms.scss
=> fix: add a border to select for better visualization crossbrowser

assets/scss/modules/_preload.scss, assets/scss/templates/_layout.scss
- Add styles to add in webapp the spinner
#Checklist
=> fix(Webapp): add styles to first loading

assets/scss/core/_reset.scss, assets/scss/core/_typography.scss, assets/scss/core/_variables.scss, assets/scss/helpers/_animations.scss, assets/scss/helpers/_colors.scss, assets/scss/modules/_buttons.scss, assets/scss/modules/_dropdown.scss, assets/scss/modules/_language.scss
=> fix: add ancestor on missing components

assets/scss/templates/_signup.scss
Related to: https://github.com/FromDoppler/doppler-webapp/pull/919
#Checklist
=> fix: padding adjustment in signup mobile

assets/scss/modules/_tabs.scss
=> fix: adjust z-index to see the background

build-n-publish-w-docker.sh, build-n-release-w-docker.sh
=> feat(App): add setup to new CDN

assets/scss/templates/_header.scss
- fix header cm logo in webapp when the cm user dont have logo and only have the name
#Checklist
=> fix(webapp): header cm logo styles

assets/js/main.js, assets/scss/modules/_accordion.scss, assets/templates/accordion-component.html, assets/templates/partials/_navigation.html
**In a column in three and two:**
**Responsive:**
To see: http://cdn.fromdoppler.com/doppler-ui-library/build892/accordion-component.html
#Checklist
=> feat: add the accordion component

build-n-publish-w-docker.sh, build-n-release-w-docker.sh
=> fix(Docker): remove akamai from dockerfiles

assets/img/ribbon-plan.svg, assets/scss/helpers/_colors.scss, assets/scss/modules/_card.scss, assets/scss/templates/_doppler-plus.scss, assets/templates/cards-component.html, assets/templates/doppler-plus.html, assets/templates/partials/_navigation.html
- the pages for the cards and for the doppler plus layout were created
- links to library navigation added
- doppler plus and cards component html created
- four classes were created to modify the position of the ribbons
- the hover effect of the cards was created
- "Data-ribbon" is used to edit the contents of the ribbon
https://cdn.fromdoppler.com/doppler-ui-library/build918/cards-component.html
#Checklist
=> feat(cards): add the ribbon image

assets/scss/helpers/_colors.scss, assets/scss/modules/_accordion.scss, assets/scss/modules/_card.scss, assets/scss/modules/_tabs.scss, assets/scss/templates/_doppler-plus.scss, assets/templates/doppler-plus.html
- doppler plus general layout created
- the free plan was added to the cards
- improved accordion icons for frequently asked questions
https://cdn.fromdoppler.com/doppler-ui-library/build924/doppler-plus.html
#Checklist
=> feat: doppler plus general layout created

assets/scss/modules/_card.scss, assets/scss/modules/mixins/_ribbon.scss, assets/templates/cards-component.html, assets/templates/doppler-plus.html
Removal of "data" attributes to manifest a graphical representation, as a bad practice. The "data" attributes are for the manipulation of non-visible data.
docs:
http://microformats.org/wiki/faq#Q:_When_should_I_use_a_microformat.3F_What_are_they_for.3F
https://developer.mozilla.org/es/docs/Learn/HTML/como/Usando_atributos_de_datos#:~:text=Los%20atributos%20data%2D*%20permiten,en%20el%20DOM%20o%20Node.
Look:
https://cdn.fromdoppler.com/doppler-ui-library/build927/cards-component.html
#Checklist
=> fix: stakeout of card component

assets/scss/core/_variables.scss, assets/scss/modules/_card.scss, assets/templates/cards-component.html, assets/templates/doppler-plus.html
Price and button alignment is maintained with less content
#Checklist
=> fix(cards-component)

assets/scss/templates/_doppler-plus.scss
=> fix: fix banner for doppler

assets/scss/modules/_tooltip.scss
=> fix: fix in tooltip

assets/scss/modules/_card.scss, assets/scss/templates/_doppler-plus.scss, assets/templates/colors-component.html, assets/templates/doppler-plus.html
=> fix: add button to compare plans

assets/scss/modules/_forms.scss, assets/scss/templates/_doppler-plus-plans-form.scss, assets/templates/doppler-plus-plans-form.html, assets/templates/partials/_navigation.html
**Plans Form**
**Plans, validations and messages form**
#Checklist
=> feat: add doppler plus plans form

assets/scss/modules/_forms.scss, assets/scss/templates/_doppler-plus-plans-form.scss, assets/scss/templates/_guidelines.scss, assets/templates/doppler-plus-plans-form.html, assets/templates/form_exclusive_features.html, assets/templates/partials/_navigation.html
add navigation for exclusive features
add the css for the checkboxs
display change to improve validation alignment
#Checklist
=> feat: add the exclusive features html

.gitignore, assets/scss/templates/_guidelines.scss, assets/scss/templates/_header.scss, assets/templates/header-component.html, assets/templates/nav-user-component.html, assets/templates/partials/_navigation.html
- Add new styles and layout to user right menu.
CM: Profile
CM: User
Demo
Enterprise: suscribers
Highvolume: emails
Standard: suscribers
Prepaid
Free
#Checklist
=> feat(header-component): apply new styles

assets/scss/modules/_card.scss, assets/scss/templates/_doppler-plus-plans-form.scss, assets/templates/doppler-plus-plans-form.html, assets/templates/form_exclusive_features.html
**Modification that the icons are part of the class**
#Checklist
=> fix: modification that the icons are part of the class

assets/scss/modules/_tabs.scss, assets/scss/templates/_doppler-plus.scss, assets/templates/doppler-plus.html, assets/templates/partials/_navigation.html, assets/templates/plan-calculator.html
**Modification of calculator tabs
Creation of the plan calculator page**
#Checklist
=> feat: modification of calculator tabs

assets/js/main.js, assets/scss/templates/_doppler-plus.scss, assets/templates/doppler-plus.html, assets/templates/plan-calculator.html, assets/templates/tabs-component.html
Look: https://cdn.fromdoppler.com/doppler-ui-library/build992/plan-calculator.html
#Checklist
=> feat: building plan calculator screen

assets/scss/templates/_doppler-plus.scss
arrangement of paddings in tabs
related to: https://github.com/FromDoppler/doppler-webapp/pull/1110
#Checklist
=> fix: fix in plan calculator

assets/scss/templates/_doppler-plus.scss
related to: https://github.com/FromDoppler/doppler-webapp/pull/1110
#Checklist
=> fix: text align title suscriptions

assets/scss/modules/_tooltip.scss, assets/scss/templates/_doppler-plus.scss, assets/templates/plan-calculator.html
=> fix: fix in tooltip component

assets/scss/modules/_accordion.scss, assets/templates/subscriber-history.html, assets/templates/table-component.html
**Fix of icons in tables and tooltips with images
icon arrow arrangement in faq**
👁️‍🗨️  you can see:
https://cdn.fromdoppler.com/doppler-ui-library/build1010/table-component.html
https://cdn.fromdoppler.com/doppler-ui-library/build1010/subscriber-history.html
https://cdn.fromdoppler.com/doppler-ui-library/build1010/doppler-plus.html
**icons in table:**
**img in tooltip:**
**icon arrow in faq:**
#Checklist
=> Fix of icons in tables and tooltips with images

assets/scss/modules/_tooltip.scss, assets/scss/templates/_doppler-plus.scss, assets/scss/templates/_guidelines.scss, assets/templates/plan-calculator.html, assets/templates/tooltip-component.html
https://cdn.fromdoppler.com/doppler-ui-library/build1022/plan-calculator.html
#Checklist
=> fix: tooltip alignment regardless of size

assets/scss/templates/_doppler-plus.scss
elimination of paddings from subscribers' main box
#Checklist
=> fix: elimination of paddings from subscribers' main box

.gitignore, assets/scss/templates/_guidelines.scss, assets/scss/templates/_header.scss, assets/templates/header-component.html, assets/templates/nav-user-component.html, assets/templates/partials/_navigation.html
=> fix(HeaderMenu): add new styles

assets/scss/modules/_tooltip.scss
=> fix in graph of day of week and hours of advanced reports

assets/scss/modules/_pagination.scss, assets/templates/subscriber-history.html
=> fix: add buttons in the paginator

assets/scss/modules/_tooltip.scss, assets/scss/templates/_doppler-plus.scss, assets/templates/plan-calculator.html
**Font corrections in plan calculator**
- **font correction in tooltip**
- **correction of sources in the subscription title**
- **font correction in plan disclaimer**
#Checklist
=> fix: font corrections in plan calculator

assets/scss/modules/_pagination.scss, assets/templates/subscriber-history.html
**No jumps**
**Add title tag**
#Checklist
=> feat(pagination): adaptation of the paging component

assets/scss/templates/_header.scss
=> fix(UserMenu):  prepaid and monthly plan ui

assets/scss/templates/_doppler-plus.scss, assets/templates/plan-calculator.html
👁️ : https://cdn.fromdoppler.com/doppler-ui-library/build1045/plan-calculator.html
#Checklist
=> feat: move message to user in plan calculator

assets/scss/modules/_tooltip.scss
=> fix: resize tooltip

assets/scss/modules/_tooltip.scss, assets/scss/templates/_guidelines.scss
Tooltip fix to try to use it in doppler main lists
#Checklist
=> fix: tooltip fix for doppler main lists

assets/scss/templates/_header.scss
=> fix(Header): user menu styles monthly plan

assets/scss/templates/_doppler-plus-plans-form.scss, assets/templates/doppler-plus-plans-form.html
=> feat: add the option "I don't know" in the Plan form for agencies

assets/scss/modules/_card.scss
=> fix: remove display none from doppler plus cards

assets/scss/templates/_doppler-plus-plans-form.scss
=> fix: alignment of volume of shipments per month in agency plan

assets/scss/modules/_tooltip.scss
=> fix: doppler tooltip fix

assets/scss/templates/_doppler-plus.scss
**Before:**
**After:**
#Checklist
=> fix: change the orientation of the arrow in the animation

package.json
=> fix: added one more level of depth in the packagejson task for sass

assets/js/main.js, assets/scss/modules/_tables.scss, assets/templates/subscriber-history.html
- Add GDPR table with dropdown
- The accessibility of the table was respected.
- The zebra of the table was changed.
- All use cases and their interaction are shown.
- validated with design. @santiagopaolucci
To see: https://cdn.fromdoppler.com/doppler-ui-library/build1118/subscriber-history.html
#Checklist
=> feat: Add GDPR table with dropdown.

assets/scss/templates/_subscriber-history.scss, assets/templates/subscriber-history.html
kreitech boys look @josedutra @bravoy93:
https://cdn.fromdoppler.com/doppler-ui-library/build1127/subscriber-history.html
#Checklist
=> feat: add button download full history

assets/scss/modules/_tables.scss, assets/scss/templates/_subscriber-history.scss, assets/templates/subscriber-history.html
Add unexpected error and no response
Replacement of links by buttons
Validated with design @mdirago
Demo: https://cdn.fromdoppler.com/doppler-ui-library/build1136/subscriber-history.html
#Checklist
=> feat: add unexpected error and no response

assets/scss/modules/_tables.scss
@mdirago look!
https://cdn.fromdoppler.com/doppler-ui-library/build1142/subscriber-history.html
#Checklist
=> feat: remove animation on unexpected error from tables

assets/scss/modules/_tables.scss, assets/templates/subscriber-history.html
👀 https://cdn.fromdoppler.com/doppler-ui-library/build1150/subscriber-history.html
@bravoy93 
#Checklist
=> feat: field overlap in dropdown tables

assets/js/MenuItemLinks.js, assets/js/main.js, assets/scss/modules/_buttons.scss, assets/templates/buttons-component.html
- add the switch component
- add slide component
- add the slide double component
#Checklist
=> feat: add the switch component

package.json
- Fix error when run watch-all and update a JS file. 
#Checklist
=> fix: add JS constant in watch all script

assets/scss/core/_reset.scss, assets/scss/core/_variables.scss
=> feat: font size change

assets/scss/modules/_tables.scss, assets/templates/subscriber-history.html
=> feat: icons alignment

assets/scss/modules/_tables.scss
=> feat: property settings for icons

assets/scss/modules/_images.scss, assets/scss/templates/_subscriber-history.scss, assets/templates/subscriber-history.html
Related to: https://github.com/FromDoppler/doppler-webapp/pull/1418
#Checklist
=> fix: class fix for icons and margin correction

assets/scss/modules/_forms.scss, assets/templates/contact-policy.html, assets/templates/partials/_navigation.html
https://cdn.fromdoppler.com/doppler-ui-library/build1227/contact-policy.html
#Checklist
=> DW-954 creation of contact policy layout

assets/scss/modules/_forms.scss, assets/templates/contact-policy.html
=> fix: add validations and states to the contact policy form

assets/scss/templates/_header.scss, assets/templates/nav-user-component.html
https://cdn.fromdoppler.com/doppler-ui-library/build1236/nav-user-component.html
#Checklist
=> feat: add pending request status with tooltip in user menu

assets/js/main.js
=> fix: bind the accordion events to the body for its correct functioning

assets/scss/templates/_big-query.scss, assets/templates/big-query.html, assets/templates/contact-policy.html
See here: https://cdn.fromdoppler.com/doppler-ui-library/build1257/contact-policy.html
#Checklist
=> DW-999 add cloud tags for policy contact-policy

assets/scss/templates/_header.scss
=> fix: add line height in p nav user

assets/scss/templates/_payment-process.scss, assets/templates/partials/_navigation.html, assets/templates/payment-process.html
=> DW-968 Layout payment process - contact information form

assets/scss/modules/_forms.scss, assets/templates/big-query.html
=> fix: border style in inputs for bigquery

assets/scss/modules/_tooltip.scss, assets/scss/templates/_header.scss
=> fix: request alignment sent in nav user

assets/scss/helpers/_colors.scss, assets/scss/modules/_forms.scss, assets/scss/templates/_payment-process.scss, assets/templates/payment-process.html
Add billing information form
Check: https://cdn.fromdoppler.com/doppler-ui-library/build1269/payment-process.html
#Checklist
=> DW-1013 billing information form

assets/js/main.js, assets/scss/templates/_list-selection.scss, assets/templates/contact-policy.html
https://cdn.fromdoppler.com/doppler-ui-library/build1285/contact-policy.html
#Checklist
=> feat: add exclude list modal for contact policy

assets/js/main.js, assets/scss/templates/_list-selection.scss, assets/templates/contact-policy.html
https://cdn.fromdoppler.com/doppler-ui-library/build1287/contact-policy.html
#Checklist
=> feat: add modal without list and modal error

assets/scss/modules/_tooltip.scss, assets/scss/templates/_doppler-plus.scss, assets/templates/plan-calculator.html
=> fix: adjust information icon size

assets/scss/templates/_doppler-plus.scss, assets/templates/doppler-plus.html
=> feat: add list element inside promo banner

assets/scss/modules/_messages.scss
https://cdn.fromdoppler.com/doppler-ui-library/build1310/index.html
**BUG**
**FIX**
#Checklist
=> fix: fix in flashcards

assets/scss/modules/_carousel.scss, assets/scss/modules/_messages.scss, assets/scss/templates/_dashboard.scss, assets/scss/templates/_guidelines.scss, assets/templates/carousel-component.html, assets/templates/dashboard.html, assets/templates/index.html, assets/templates/partials/_navigation.html
=> feat: create pages to develop dashboard

assets/scss/templates/_payment-process.scss, assets/templates/payment-process.html
- Card field adjustments (sizes and validations)
- Add disabled status in renewal types
- Add a list of items to the end of the form
- Adjustments in the Summary font colors and size and shape of the total price
#Checklist
=> fix: fin in credit card and summary

assets/scss/templates/_payment-process.scss, assets/templates/payment-process.html
- transfer payment
- payment by mercado pago
#Checklist
=> feat: add payment methods

assets/scss/modules/_carousel.scss
Fix in the content box of the carousel
#Checklist
=> feat: add adjustment in the content box of the carousel to fit the text

assets/scss/modules/_forms.scss, assets/templates/component-elements-checked.html, assets/templates/partials/_navigation.html
-add html page for component
-add navigation
#Checklist
=> feat: isolate component radio button

assets/scss/templates/_payment-process.scss
=> fix: fix form billing information

assets/scss/templates/_header.scss
=> feat: add sticky message in header

assets/scss/modules/_forms.scss
=> fix: fix checkbox

assets/scss/templates/_header.scss
=> fix: fix message sticky

assets/scss/modules/_buttons.scss
add justify content center in button--centered-loading 
#Checklist
=> fix: add justify content center

assets/scss/templates/_dashboard.scss, assets/templates/dashboard.html
class change for a more generic and reusable use of the column first steps
#Checklist
=> fix: class change for a more generic and reusable use

assets/scss/templates/_payment-process.scss, assets/templates/payment-process.html
See:
https://cdn.fromdoppler.com/doppler-ui-library/build1391/payment-process.html
#Checklist
=> feat: add status in promocode and validations

assets/scss/templates/_dashboard.scss, assets/templates/dashboard.html
=> feat: add link to the title of first steps

assets/scss/templates/_dashboard.scss, assets/templates/dashboard.html
- Add a margin bottom for the p elements of the postcard
- Changed the opacity of the overlay to 0.9
#Checklist
=> fix: add a margin bottom for the p elements of the postcard

assets/templates/payment-process.html
Add back button in the new checkout
See: https://cdn.fromdoppler.com/doppler-ui-library/build1411/payment-process.html
#Checklist
=> feat: add back button in the new checkout

assets/scss/modules/_forms.scss, assets/templates/payment-process.html
=> fix: add fix in form checkout status disabled in fields

assets/scss/templates/_doppler-plus.scss, assets/templates/plan-calculator.html
=> feat: add a disabled state for subscription discounts

assets/templates/partials/_navigation.html
=> feat: remove push notification html

assets/js/main.js, assets/scss/modules/_button-group.scss, assets/scss/modules/_buttons.scss, assets/templates/buttons-component.html
=> feat: add button component with menu for editors

assets/scss/modules/_button-group.scss, assets/templates/buttons-component.html
- menu styling settings for the webapp
#Checklist
=> fix: changing anchor elements by button for the editors menu

assets/scss/modules/_button-group.scss, assets/templates/buttons-component.html
=> fix: add support for buttons and links in menu editors

assets/scss/modules/_button-group.scss, assets/templates/buttons-component.html
=> fix: change of role in the editors menu

assets/scss/modules/_ribbons.scss
=> fix: add ribbon styles

npm-shrinkwrap.json, package-lock.json, package.json
This reverts commit b12b8d626c9e6fc097143efdde4dc58bc98534d6.
=> Revert "fix(deps-dev): bump cpy-cli from 3.1.1 to 4.1.0"

assets/scss/templates/_header.scss, assets/templates/header-component.html
=> fix: fix in doppler responsive menu
