assets/scss/core/_base.scss, assets/scss/modules/_buttons.scss, assets/templates/index.html
Adding disabled and grey button styles
See demo in https://cdn.fromdoppler.com/doppler-ui-library/build97/
Updated:
=> Adding disabled and grey button styles

assets/scss/templates/_header.scss, assets/scss/utilities/_ellipsis.scss
Besides removing the styles that were unused and were affecting the structure for the user menu, I've created a mixin to handle ellipsis on elements.
This mixin is intended for internal usage, meaning that this will help Library creators do ellipsis on elements based on given attrs.
=> Dbr 100 user menu bug

assets/scss/core/_base.scss, assets/scss/modules/_buttons.scss, assets/scss/modules/_forms.scss, assets/scss/templates/_signup.scss
Todos los ajustes fueron validados con Santiago Paolucci.
1. icono ojo sacar itálica y colocar itálica solo al "mostrar"
2. alinear el icono del ojo y sacar line-height
3. agregar cursor pointer al link de mostrar contraseña
4. modificar en main-panel padding lateral de 36px por 48px
5. quitar margen lateral del botón
6. agregar a la clase .button--round, font-weight: 600;
7. agregar al texto legal la fuente próxima nova
8. cambiar la tipografía de formularios a próxima nova solo para las paginas publicas
9. cambiar en el foco del input tipografía a itálica
https://cdn.fromdoppler.com/doppler-ui-library/build186/signup.html
=> feat: visual adjustment in sign up

assets/scss/core/_base.scss, assets/templates/forgot-password.html, assets/templates/login.html, assets/templates/modal.html, assets/templates/signup.html
Hey team! I am touching SCSS hehe!
The idea is unifying general form errors and field errors, and in both of them support basic HTML: p, span, strong, em, links, etc. 
By the moment, li is not being supported, because I do not need it yet.
Could you review it?
Thanks @GusBaamonde for your help!
@mvillaseco, @cbernat, @IgnacioRodrigues, @damianmuti 
You can review it in (in the mockups the font is wrong, in build 224 it is fixed)
* https://cdn.fromdoppler.com/doppler-ui-library/build224/signup.html
* https://cdn.fromdoppler.com/doppler-ui-library/build224/login.html
=> DBR-213 - General form messages

assets/scss/templates/_header.scss, assets/scss/templates/_reportes.scss
=> feat: remove uppercase from user menu

assets/scss/templates/_signup.scss
For the login, signup, and forgot password pages, register/signup links after the main header should inherit their font-size.
=> fix: links should inherit font-size

assets/scss/core/_typography.scss
Despite fixing this issue, I've added a small improvement to prevent these kind of issues in the future because of specificity with the `font` declaration.
=> fix: issues with line-height and font declaration specificity

assets/scss/templates/_reportes.scss
- Add min height to show spinner inside the box
=> fix: spinner in reports ranking

assets/js/MenuItemLinks.js, assets/js/PopupMenuLinks.js, assets/js/dropdown.js, assets/js/main.js, assets/scss/modules/_dropdown.scss, assets/scss/modules/_language.scss, assets/templates/forgot-password.html, assets/templates/login.html, assets/templates/signup.html
One improvement that we've detected on the login/signup/forgot-password pages was that those pages are not keyboard accessible.
What we've ended up deciding to do was to refactor what we needed for keyboard accessibility to work, including dropdown menus.
Instead of creating something from scratch, I've checked what W3C says about dropdown menus and, to our fortune, they provide some javascript+html+css standalone modules for this to properly work, so this PR is based on that.
=> refactor: dropdowns now are accessible with keyboard

assets/scss/core/_reset.scss
To homogenize the scrollbar, it allows us to manipulate it cross browser in a uniform way.
=> feat: remove hack in scrollbar

assets/scss/templates/_header.scss
Se observa una diferencia en el padding lateral de webapp en relación al resto de la app
http://jira.makingsense.com/browse/DBR-342
=> feat: remove lateral margin from the menu

assets/js/main.js, assets/scss/templates/_header.scss
DBR-341 When header is collapsed, user lateral menu is hidden
=> feat: remove overflow hidden from header main

assets/js/main.js
Because react does not override inline styles there was an issue with the header.  
Scenario: when in reports, hover another menu without sub items and then go to shopify, the result was that the menu did not hide when in shopify. 
http://cdn.fromdoppler.com/doppler-ui-library/build391/header.html
=> fix(header): add classes instead of styles to hide header submenu

assets/scss/templates/_signup.scss
Image background adjustment to eliminate white space
Related to: http://jira.makingsense.com/browse/DBR-346
**Before**
**After**
=> fix: image background adjustment to eliminate white space

assets/scss/core/_reset.scss, assets/scss/core/_typography.scss, assets/scss/modules/_buttons.scss
- The variable --font-family is deleted, it has no use
- the variable dp-font has as parameter ('font-weight', 'font-size', 'font-family')
- The titles had this variable + the declaration of font-weight + level-sizes.
- The variable dp-font of the h1, h2, h3, h4, h5, h6 was deleted by duplicate code.
- White color is added in the buttons hover
=> fix: to correct a hierarchy of inheritances in fonts

assets/scss/modules/_tables.scss
The separation line in the header of the table that was within `<a>` was removed, the separation line now depends on each `<th>`, so we avoid collecting items that are only decorative.
Ready @cbernat ! :)
=> fix(table component)

build-n-release-w-docker.sh, build-w-docker.sh
* Delete `dist` folder inside docker context
It is to avoid issues in Jenkins who is trying to delete with `jenkins` user files created as `root` inside docker context
* Force public permissions to `dist` files to allow easily delete them
=> Fix build cleanup

assets/scss/modules/_messages.scss, assets/scss/templates/_integrations.scss, assets/templates/partials/_msj-component.html
Include colors according to the message
Remove margin 0 in the `p`
=> fix: Include anchors in messages

assets/scss/templates/_integrations.scss, assets/scss/templates/_layout.scss
Use flexbox for footer alignment
=> fix: footer for pages with little content

README.md, gulpfile.js
- Added title in docs with link to style guide.  (Doppler UI Library)
A link to documentation in style guide will be provided in next layout. 
- Added documentation link in readme.
https://cdn.fromdoppler.com/doppler-ui-library/build484/documentation/
=> Documentation improvement

assets/scss/modules/_box.scss
=> fix(dp-box): remove the overflow-hidden in the box-shadow mixin

assets/scss/modules/_grid-system.scss, assets/templates/grid-system-component.html
Add the dp-boxshadow class error to handle errors inside dp-box-shadow boxes
Related to: https://github.com/FromDoppler/doppler-webapp/pull/580
#Checklist
=> fix: Add the dp-boxshadow class error

assets/scss/modules/_grid-system.scss, assets/templates/grid-system-component.html
=> fix: Add gray message to user in dp-box-shadow

assets/scss/core/_reset.scss, assets/scss/modules/_forms.scss, assets/scss/modules/_language.scss
#Checklist
Related to: https://github.com/FromDoppler/doppler-webapp/pull/618
=> fix: outline function enabled for keyboard navigation in the select

build-n-release-w-docker.sh
Semantic release needs dist folder created with build to generate the tag, this is a bit different in doppler webapp. 
#Checklist
@andresmoschini I'm tagging you here just in case.
=> fix(semantic-release): fixed script

Dockerfile, npm-shrinkwrap.json, package.json
- Add one more json file to install the dependencies to node version 12 and dont change gulp 3.
The explanation is here: https://timonweb.com/posts/how-to-fix-referenceerror-primordials-is-not-defined-error/
=> fix(Node): cannot use more than 10 version

assets/scss/helpers/_colors.scss, assets/scss/modules/_buttons.scss, assets/scss/modules/_forms.scss, assets/scss/templates/_guidelines.scss, assets/templates/colors-component.html, assets/templates/signup.html
Improvement in the pseudo-class: focus to be able to navigate the forms with tab and improve our accessibility
#Checklist
Look: http://cdn.fromdoppler.com/doppler-ui-library/build871/signup.html
=> feat: improvement in the pseudo-class: focus

assets/scss/modules/_tooltip.scss
**remove tooltip in small resolutions**
👁️‍🗨️ : https://cdn.fromdoppler.com/doppler-ui-library/build1023/plan-calculator.html
#Checklist
=> fix: remove tooltip in small resolutions

assets/scss/modules/_tables.scss
Fix vertical alignment text in blocked segment/lists tag in the segments and lists grid in app
=> fix(DopplerApp): blocked segment tag styles in segments grid

assets/scss/modules/_tooltip.scss, assets/scss/templates/_header.scss, assets/templates/header-component.html, assets/templates/nav-user-component.html, assets/templates/tooltip-component.html
=> fix: tooltip left class for user menu

.gitattributes
_* Fix(.gitattributes): add font extensions as binary to fix git extension binaries error._
=> Fix(.gitattributes): add font extensions as binary

assets/scss/modules/_forms.scss
Remove max width from radio button component
Related: https://github.com/MakingSense/Doppler/pull/8778
=> fix: remove max width

assets/scss/templates/_messages-header.scss, assets/templates/account-message-component.html
See:
https://cdn.fromdoppler.com/doppler-ui-library/build1388/account-message-component.html
#Checklist
=> fix: fix in message for user add orange color to button
